# Generated by Django 4.2.6 on 2023-10-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Время приготовления'),
        ),
    ]
