# Generated by Django 4.2.6 on 2023-10-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_text_alter_recipe_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurements',
            field=models.CharField(default='грамм', max_length=200, verbose_name='Единица измерения'),
        ),
    ]
