# Generated by Django 4.2.6 on 2023-10-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_shoppinglist_unique_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Рецепт в Избранном', 'verbose_name_plural': 'Рецепты в Избранном'},
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_favorite',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_favorite'),
        ),
    ]
