# Generated by Django 4.2.6 on 2023-10-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_favorite_recipe_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurements',
            new_name='measurement_unit',
        ),
    ]
