# Generated by Django 4.2.6 on 2023-10-11 17:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#49B64E', image_field=None, max_length=25, samples=None, verbose_name='Цвет'),
        ),
    ]
